### ISSUE TITLE
Feature: Make Stylelint a Peer Dependency

### ISSUE THREAD

**Issue by keplersj** [keplersj/jest-runner-stylelint#11]

**Comment by montezume** [comment]
This would be nice, right now we are forced to use yarn resolutions so we can use this runner with css in js.

**Comment by keplersj** [comment]
@montezume Technically, the CSS-in-JS issue is resolved with #25 and v1.0.1 now. I will be pushing a v2.0.0 soon that makes stylelint a peer dep.

**Comment by keplersj** [comment]
Resolved in 7b3438c. Hitting npm soon.
