### ISSUE TITLE
Seems to be running multiple times

### ISSUE THREAD

**Issue by lakshyaranganath** [keplersj/jest-runner-stylelint#4]
When I run jest with `jest-runner-stylelint` setup as so
```
displayName: 'stylelint',
runner: 'jest-runner-stylelint',
testMatch: ['<rootDir>/src/**/*.js'],
```

Here is the terminal output (shortened)
<img width="487" alt="screen shot 2017-12-20 at 10 24 46 am" src="https://user-images.githubusercontent.com/7546892/34191850-20bdff38-e570-11e7-88bc-1be83906c7f0.png">

Either it's running multiple times or its just that the terminal output redrawing seems to make it look like that.

**Comment by keplersj** [comment]
I believe that's just how Jest redraws. I've always had that with happen with Jest.

**Comment by lakshyaranganath** [comment]
Hey @keplersj, so I made an error in one file and ran the test again.

Looks like the error only reports once. If the lint ran multiple times, my guess is it would have also reported the error multiple times.

So you're right, it is the redraw problem.

What I think is possibly happening is the tests are starting up, but since stylelint seems to be returning a promise, they all show up as `RUNS` first, and once they resolve they're all redrawn to the output as `PASS` or `FAIL`.

Anyway I think it's a issue to be raised on Jest and maybe not here :)

Thanks again! 👍

**Comment by keplersj** [comment]
Happy to help! If you raise an issue with Jest feel free to link back here, I'd be curious to see what they say.

**Comment by lakshyaranganath** [comment]
Im going to go poke around Jest to see if someone found a way around it. 
I'll report/link back anything I find.

**Comment by rockingskier** [comment]
@lakshyaranganath I know this was a while ago but did you find a solution?  I'm seeing the same thing with jest@^24.8.0.

I've noticed it only does it when there are more tests than can be fitted on one terminal screen.  With few tests it outputs correctly.
